### ISSUE TITLE
not working here

### ISSUE THREAD

**Issue by juancresc** [jts/bam2fastq#3]
(base) ➜  lan-dic ./../sw/bam2fastq/bam2fastq -o data/landic_svevo_1.un.fastq data/landic_svevo_1.un.sam 
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[1]    19566 abort (core dumped)  ./../sw/bam2fastq/bam2fastq -o data/landic_svevo_1.un.fastq

**Comment by jts** [comment]
You're tried to pass in a sam file. This program converts bam to fastq.
